### ISSUE TITLE
[joss review] Gallery

### ISSUE THREAD

**Issue by fnattino** [SMTG-Bham/ThermoParser#85]
In the gallery I have found few examples that do not run as they are provided. Some examples:
* For [heatmaps](https://smtg-bham.github.io/ThermoParser/heatmaps.html), but also others, the `kappa-mxxxx.hdf5` is not provided, and only when checking out the Python script in the tutorial I realised how to get these files. 
* Some of the commands in the [gallery main page](https://smtg-bham.github.io/ThermoParser/gallery.html#) do not follow the correct syntax required by click to provide multiple values, e.g. :  `tp plot phonons band.yaml -c '#ff8000' -d projected_dos.dat --doscolour '#ffff00' '#00ffff' ` (should instead ends with: `--doscolour '#ffff00' --doscolour  '#00ffff'`) 
* Also, when fixing the problem above, the `projected_dos.dat` seems to include contributions for imaginary frequencies:
![tp-phonons](https://github.com/SMTG-Bham/ThermoParser/assets/49899980/539b4dd0-9d99-4909-a9b8-221b50d9a5ca)
* The command to run the ZTdiff (last CLI command on [this page](https://smtg-bham.github.io/ThermoParser/heatmaps.html))seems to be missing some files? `tp plot ztdiff ../data/zno/transport_75x75x75.json  ../data/zno/boltztrap.hdf5 -k ../data/zno/kappa-m404021.hdf5 ../data/zno/kappa-m404021.hdf5 -l MRTA -l CRTA
` 

[JOSS review issue](https://github.com/openjournals/joss-reviews/issues/6340)

**Comment by kbspooner** [comment]
* I realised I only added the explanation of this in the github readme, which didn't make it into the website docs. The relevent text has been copied into the gallery page, and in both cases a title has been added highlighting it.
* Looks like when I updated from argparse to click I updated the main tutorials and examples, but missed some of the gallery code. I've now made it so the gallery imports the bash code directly from the examples, so this won't happen again. I also updated other parts of the docs similarly.
* I actually noticed this the other day and the offending file has been replaced with the converged publication-quality data.
* Whoops, that was meant to be basno3 not zno. Now corrected.

These updates are currently in the bug-fix branch.

**Comment by fnattino** [comment]
Thanks, where and how the additional data can be downloaded is clearer now. Also thanks for fixing the issues above. 

I still have some troubles running some of the commands via the CLI, I list the issues that I get here. Could you please have a look?

## 1. Heatmaps


Running the following command:
```
tp plot ztmap ../data/zno/boltztrap.hdf5 -k ../data/zno/kappa-m404021.hdf5 -c '#800080' -d x --discrete
``` 
Leads to: 
<details>

```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/ThermoParser/bin/tp", line 8, in <module>
    sys.exit(tp_cli())
             ^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/tp/cli/cli.py", line 2265, in ztmap
    tp.plot.heatmap.add_ztmap(ax, edata, kdata=kdata, direction=direction,
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/tp/plot/heatmap.py", line 715, in add_ztmap
    cbar = add_heatmap(ax, data['temperature'], list(np.abs(data['doping'])),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/tp/plot/heatmap.py", line 254, in add_heatmap
    levels = int(levels[0])
             ^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

</details>

Also note there is one backtick "`" at the beginning of the command line in the docs. 

Also the command below:
```
tp plot kappa-target ../data/zno/boltztrap.hdf5 -c '#008080' -d x
```
Gives this error:

<details>

```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/ThermoParser/bin/tp", line 8, in <module>
    sys.exit(tp_cli())
             ^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/tp/cli/cli.py", line 1467, in kappa_target
    cbar = tp.plot.heatmap.add_kappa_target(ax, edata, zt=zt,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/tp/plot/heatmap.py", line 1020, in add_kappa_target
    cbar = add_heatmap(ax, data['temperature'], list(np.abs(data['doping'])),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/tp/plot/heatmap.py", line 304, in add_heatmap
    cbar.ax.axhline(c, color=contourcolours[i], **contourkwargs)
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/matplotlib/axes/_axes.py", line 784, in axhline
    scaley = (yy < ymin) or (yy > ymax)
              ^^^^^^^^^
TypeError: '>' not supported between instances of 'float' and 'NoneType'
```

</details>

## 2. Phonons

In the following command one of the `--doscolour` option is missing one "-":
```
tp plot phonons ../data/zno/band.yaml --dos ../data/zno/projected_dos.dat --poscar ../data/zno/POSCAR -doscolour '#d46ef9' --doscolour '#7b8eff' -c '#f0901f'
```

## 3. Waterfall

The following command:
```
tp plot waterfall ../data/basno3/kappa-m363636.hdf5 -y mfp --projected kappa
```

Gives the following error:

<details>

```

Using 300.0 K.
Traceback (most recent call last):
  File "/opt/miniconda3/envs/ThermoParser/bin/tp", line 8, in <module>
    sys.exit(tp_cli())
             ^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/tp/cli/cli.py", line 2104, in waterfall
    cbar = tp.plot.frequency.add_projected_waterfall(ax, data, y,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ThermoParser/lib/python3.11/site-packages/tp/plot/frequency.py", line 896, in add_projected_waterfall
    cbar.draw_all()
    ^^^^^^^^^^^^^
AttributeError: 'Colorbar' object has no attribute 'draw_all'. Did you mean: '_draw_all'?
```

</details>

**Comment by kbspooner** [comment]
Thanks for catching these! All are now fixed. Not sure why the last one works for me and not you, but the suggested change has the same effect and if it makes it more robust that must be a good thing.

**Comment by fnattino** [comment]
Thanks - I can confirm they all work now!
